services:
  fastapi:
    build: 
      context: .  # Build from the current directory
      dockerfile: Dockerfile.fastapi  # Optional if you have a specific Dockerfile
    ports:
      - "8000:8000"  # Expose FastAPI backend
    depends_on:
      - db  # Wait for the database service to be available
    environment:
      - DATABASE_URL=postgresql://user:password@db/gan_image_studio  # Database connection string
    command: uvicorn app:app --host 0.0.0.0 --port 8000  # Command to run FastAPI

  streamlit:
    build: 
      context: .  # Build from the current directory
      dockerfile: Dockerfile.streamlit  # Assuming you have a separate Dockerfile for Streamlit
    ports:
      - "8501:8501"  # Expose Streamlit frontend
    depends_on:
      - db  # Wait for the database service to be available
    environment:
      - FASTAPI_URL=http://fastapi:8000  # Internal communication with FastAPI
    command: streamlit run main_app.py --server.port 8501  # Command to run Streamlit

  db:
    image: postgres:13  # Use the official PostgreSQL image
    environment:
      - POSTGRES_USER=user  # Database user
      - POSTGRES_PASSWORD=password  # Database password
      - POSTGRES_DB=gan_image_studio  # Initial database to create
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Define a named volume for PostgreSQL data persistence