# Dockerfile.streamlit
FROM python:3.9

WORKDIR /app

# Install Streamlit
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit application code
COPY . .

CMD ["streamlit", "run", "main_app.py", "--server.port", "8501"]